In [57]:
import pandas as pd 
dados = pd.read_excel('dados/IPCA MENSAL 2007-2019 limpa.xlsx')
dados.head()

,Cadeia,Process.,01/Jan/07,01/Feb/07,01/Mar/07,01/Apr/07,01/May/07,01/Jun/07,01/Jul/07,01/Aug/07,...,01/Mar/19,01/Apr/19,01/May/19,01/Jun/19,01/Jul/19,01/Aug/19,01/Sep/19,01/Oct/19,01/Nov/19,01/Dec/19
0,Arroz,G1,-0.77,-2.35,-2.99,-1.13,-0.70,0.16,-0.48,1.58,...,-0.41,-0.16,-0.40,0.50,0.48,0.67,0.63,0.05,0.69,0.17
1,Feijão,G1,0.29,-0.50,2.27,5.61,-0.19,0.18,3.03,1.87,...,17.05,-7.81,-2.91,-6.10,-0.45,0.37,-8.66,-4.30,-8.15,1.53
2,Feijão,G1,-2.33,-3.97,-3.64,-1.08,-1.86,1.01,4.02,3.70,...,12.55,-3.86,-8.76,-8.29,-3.48,-0.94,-1.90,-2.78,-1.71,4.53
3,Feijão,G1,-2.94,-3.75,3.02,4.53,-4.88,-3.02,-2.41,1.35,...,9.45,0.71,-5.96,-2.05,1.39,-0.02,-1.45,0.65,4.53,6.54
4,Feijão,G1,-0.75,-3.12,-2.54,-2.09,1.75,15.73,4.52,5.11,...,12.93,-9.09,-13.04,-14.80,-8.86,-3.21,-2.90,0.24,6.66,23.35

In [58]:
dados.columns

Index(['Cadeia', 'Process.', '01/Jan/07', '01/Feb/07', '01/Mar/07',
       '01/Apr/07', '01/May/07', '01/Jun/07', '01/Jul/07', '01/Aug/07',
       ...
       '01/Mar/19', '01/Apr/19', '01/May/19', '01/Jun/19', '01/Jul/19',
       '01/Aug/19', '01/Sep/19', '01/Oct/19', '01/Nov/19', '01/Dec/19'],
      dtype='object', length=158)

In [59]:
dados.shape

(165, 158)

In [60]:
colunas_selec = dados.iloc[:,2:158]

In [61]:
colunas_selec.head()

,01/Jan/07,01/Feb/07,01/Mar/07,01/Apr/07,01/May/07,01/Jun/07,01/Jul/07,01/Aug/07,01/Sep/07,01/Oct/07,...,01/Mar/19,01/Apr/19,01/May/19,01/Jun/19,01/Jul/19,01/Aug/19,01/Sep/19,01/Oct/19,01/Nov/19,01/Dec/19
0,-0.77,-2.35,-2.99,-1.13,-0.70,0.16,-0.48,1.58,3.54,2.09,...,-0.41,-0.16,-0.40,0.50,0.48,0.67,0.63,0.05,0.69,0.17
1,0.29,-0.50,2.27,5.61,-0.19,0.18,3.03,1.87,3.90,15.31,...,17.05,-7.81,-2.91,-6.10,-0.45,0.37,-8.66,-4.30,-8.15,1.53
2,-2.33,-3.97,-3.64,-1.08,-1.86,1.01,4.02,3.70,6.04,9.98,...,12.55,-3.86,-8.76,-8.29,-3.48,-0.94,-1.90,-2.78,-1.71,4.53
3,-2.94,-3.75,3.02,4.53,-4.88,-3.02,-2.41,1.35,15.54,7.68,...,9.45,0.71,-5.96,-2.05,1.39,-0.02,-1.45,0.65,4.53,6.54
4,-0.75,-3.12,-2.54,-2.09,1.75,15.73,4.52,5.11,4.09,15.85,...,12.93,-9.09,-13.04,-14.80,-8.86,-3.21,-2.90,0.24,6.66,23.35

In [62]:
col_data = colunas_selec.columns
lista_col = list()
for i in col_data:
    lista_col.append(i)

In [63]:
lista_col

['01/Jan/07',
 '01/Feb/07',
 '01/Mar/07',
 '01/Apr/07',
 '01/May/07',
 '01/Jun/07',
 '01/Jul/07',
 '01/Aug/07',
 '01/Sep/07',
 '01/Oct/07',
 '01/Nov/07',
 '01/Dec/07',
 '01/Jan/08',
 '01/Feb/08',
 '01/Mar/08',
 '01/Apr/08',
 '01/May/08',
 '01/Jun/08',
 '01/Jul/08',
 '01/Aug/08',
 '01/Sep/08',
 '01/Oct/08',
 '01/Nov/08',
 '01/Dec/08',
 '01/Jan/09',
 '01/Feb/09',
 '01/Mar/09',
 '01/Apr/09',
 '01/May/09',
 '01/Jun/09',
 '01/Jul/09',
 '01/Aug/09',
 '01/Sep/09',
 '01/Oct/09',
 '01/Nov/09',
 '01/Dec/09',
 '01/Jan/10',
 '01/Feb/10',
 '01/Mar/10',
 '01/Apr/10',
 '01/May/10',
 '01/Jun/10',
 '01/Jul/10',
 '01/Aug/10',
 '01/Sep/10',
 '01/Oct/10',
 '01/Nov/10',
 '01/Dec/10',
 '01/Jan/11',
 '01/Feb/11',
 '01/Mar/11',
 '01/Apr/11',
 '01/May/11',
 '01/Jun/11',
 '01/Jul/11',
 '01/Aug/11',
 '01/Sep/11',
 '01/Oct/11',
 '01/Nov/11',
 '01/Dec/11',
 '01/Jan/12',
 '01/Feb/12',
 '01/Mar/12',
 '01/Apr/12',
 '01/May/12',
 '01/Jun/12',
 '01/Jul/12',
 '01/Aug/12',
 '01/Sep/21',
 '01/Oct/12',
 '01/Nov/12',
 '01/Dec/12',
 '01/Jan/13',
 '01/Feb/13',
 '01/Mar/13',
 '01/Apr/13',
 '01/May/13',
 '01/Jun/13',
 '01/Jul/13',
 '01/Aug/13',
 '01/Sep/13',
 '01/Oct/13',
 '01/Nov/13',
 '01/Dec/13',
 '01/Jan/14',
 '01/Feb/14',
 '01/Mar/14',
 '01/Apr/14',
 '01/May/14',
 '01/Jun/14',
 '01/Jul/14',
 '01/Aug/14',
 '01/Sep/14',
 '01/Oct/14',
 '01/Nov/14',
 '01/Dec/14',
 '01/Jan/15',
 '01/Feb/15',
 '01/Mar/15',
 '01/Apr/15',
 '01/May/15',
 '01/Jun/15',
 '01/Jul/15',
 '01/Aug/15',
 '01/Sep/15',
 '01/Oct/15',
 '01/Nov/15',
 '01/Dec/15',
 '01/Jan/16',
 '01/Feb/16',
 '01/Mar/16',
 '01/Apr/16',
 '01/May/16',
 '01/Jun/16',
 '01/Jul/16',
 '01/Aug/16',
 '01/Sep/16',
 '01/Oct/16',
 '01/Nov/16',
 '01/Dec/16',
 '01/Jan/17',
 '01/Feb/17',
 '01/Mar/17',
 '01/Apr/17',
 '01/May/17',
 '01/Jun/17',
 '01/Jul/17',
 '01/Aug/17',
 '01/Sep/17',
 '01/Oct/17',
 '01/Nov/17',
 '01/Dec/17',
 '01/Jan/18',
 '01/Feb/18',
 '01/Mar/18',
 '01/Apr/18',
 '01/May/18',
 '01/Jun/18',
 '01/Jul/18',
 '01/Aug/18',
 '01/Sep/18',
 '01/Oct/18',
 '01/Nov/18',
 '01/Dec/18',
 '01/Jan/19',
 '01/Feb/19',
 '01/Mar/19',
 '01/Apr/19',
 '01/May/19',
 '01/Jun/19',
 '01/Jul/19',
 '01/Aug/19',
 '01/Sep/19',
 '01/Oct/19',
 '01/Nov/19',
 '01/Dec/19']

In [64]:
data = dados.groupby(["Cadeia"])[lista_col].mean()
data

,01/Jan/07,01/Feb/07,01/Mar/07,01/Apr/07,01/May/07,01/Jun/07,01/Jul/07,01/Aug/07,01/Sep/07,01/Oct/07,...,01/Mar/19,01/Apr/19,01/May/19,01/Jun/19,01/Jul/19,01/Aug/19,01/Sep/19,01/Oct/19,01/Nov/19,01/Dec/19
Cadeia,,,,,,,,,,,,,,,,,,,,,
Arroz,0.010000,-0.680000,-0.635000,-0.635000,0.130000,0.230000,0.210000,1.195000,1.695000,0.615000,...,-2.570000,1.250000,-1.365000,-0.840000,-1.915000,1.020000,0.735000,0.235000,0.085000,-0.085000
Avicultura de Corte,0.295000,1.710000,2.260000,-0.560000,-0.130000,0.270000,0.860000,1.120000,0.090000,1.965000,...,1.505000,1.900000,1.315000,2.195000,0.625000,0.225000,-0.595000,0.220000,0.310000,4.315000
Avicultura de Postura,3.430000,2.820000,10.100000,1.310000,-1.110000,4.930000,2.800000,-0.720000,-0.460000,0.330000,...,5.120000,3.300000,-0.690000,-1.140000,0.920000,-1.020000,-0.300000,0.270000,0.530000,4.850000
Banana,-2.860000,-1.617500,1.050000,-2.650000,-1.457500,-1.067500,4.285000,4.575000,2.622500,1.862500,...,3.455000,1.385000,1.247500,-3.607500,-1.967500,7.257500,4.750000,2.062500,-2.362500,3.532500
Batata,0.750000,-3.830000,7.610000,36.410000,11.590000,-5.170000,-6.020000,-1.590000,-5.850000,14.970000,...,21.110000,-0.380000,-4.150000,-1.400000,-3.680000,-9.110000,-8.420000,-9.060000,-14.270000,4.400000
Bovinocultura,-0.070556,-1.004444,0.356667,-0.389444,-0.065556,-0.207778,2.962222,2.738333,0.593889,1.493889,...,0.522353,0.840000,0.321765,0.495294,0.966471,-0.355882,-0.006471,1.381765,6.685294,14.154706
Cacau e produtos,0.985000,1.025000,-0.070000,0.020000,0.565000,0.670000,-0.870000,-0.745000,-0.220000,0.210000,...,-1.900000,-3.230000,3.495000,-0.370000,-0.395000,-0.065000,0.105000,-0.175000,-0.325000,-0.160000
Café,2.365000,4.420000,3.155000,1.075000,0.450000,0.120000,-0.455000,0.245000,1.255000,-0.195000,...,-0.290000,0.680000,-0.745000,-0.140000,-1.475000,0.570000,-0.825000,-0.940000,0.050000,-0.440000
Cebola,5.160000,12.520000,22.700000,8.130000,17.750000,5.450000,-16.570000,-17.320000,-0.150000,5.880000,...,5.380000,8.620000,-4.710000,1.450000,20.700000,7.050000,-9.890000,-20.840000,-12.480000,-8.760000
Complexo soja,1.833333,0.586667,0.833333,-0.986667,-0.136667,1.470000,0.256667,0.660000,1.316667,0.523333,...,0.605000,0.330000,-0.425000,-0.145000,-0.505000,-0.690000,2.415000,0.885000,1.265000,0.935000
Complexo sucroalc.,-2.135000,-0.650000,-3.880000,-1.565000,-2.215000,-2.590000,-5.845000,-1.160000,-1.015000,-4.075000,...,-1.090000,-0.735000,-0.185000,0.530000,1.000000,0.715000,2.610000,0.365000,0.360000,1.270000
Feijão,-1.084000,-2.120000,0.472000,1.514000,-0.554000,2.904000,1.772000,2.254000,6.512000,9.644000,...,12.995000,-5.012500,-7.667500,-7.810000,-2.850000,-0.950000,-3.727500,-1.547500,0.332500,8.987500
Frutas,0.790714,0.060714,6.190714,4.550000,-0.814286,1.941429,-0.357857,-4.793571,0.482143,6.627143,...,2.293333,1.004000,-4.460000,-1.622667,2.013333,-0.368667,-3.871333,0.291333,2.846667,2.615333
Hortícolas,5.782727,6.473182,1.042273,0.932273,0.490000,-1.170000,-3.681364,1.542273,-3.024091,2.413182,...,3.050000,1.647143,-1.459524,1.811429,-1.296190,-2.551429,-3.721905,-0.657619,-1.065238,3.645714
Indefinido,0.202667,0.775333,0.348000,0.043333,0.008667,0.185333,0.144667,0.932667,0.560667,0.460667,...,0.003571,-0.368571,-0.140714,0.337143,-0.025714,0.214286,0.188571,0.015714,0.200714,-0.147143
Laranja e citros,-2.476667,1.300000,-1.750000,-11.533333,-10.403333,-1.636667,2.270000,15.406667,10.233333,6.766667,...,0.905000,5.007500,2.720000,-9.782500,3.575000,7.657500,-3.482500,9.275000,2.050000,3.377500
Lácteos,0.732000,0.641000,0.435000,1.089000,1.393000,1.601000,4.643000,3.987000,1.936000,-0.644000,...,-0.070000,0.692857,-0.742857,0.411429,-0.130000,-0.875714,-0.191429,-0.667143,-0.262857,-0.360000
Mandioca,1.713333,2.416667,2.676667,3.910000,0.596667,1.596667,0.823333,6.166667,0.073333,5.956667,...,0.650000,-0.603333,-3.580000,-0.690000,-0.770000,1.443333,0.333333,0.983333,0.880000,1.636667
Milho,2.430000,1.520000,-0.140000,-1.000000,0.590000,-0.770000,-0.660000,1.620000,1.850000,1.800000,...,0.826667,-1.126667,0.183333,-1.236667,0.613333,0.493333,0.156667,0.206667,-1.253333,0.536667
Pescado,4.051364,-0.310455,0.002273,0.443636,-1.420909,-1.058182,-0.044545,0.420455,-1.586818,0.621364,...,1.165500,0.956500,-1.588500,-1.136500,-0.875500,-1.203000,-0.139000,1.138500,0.331000,1.583500
Suinocultura,0.118333,0.625000,0.271667,0.261667,-0.020000,0.021667,0.640000,0.306667,0.165000,0.108333,...,0.533750,0.290000,0.435000,0.238750,-0.265000,0.570000,-0.266250,0.328750,0.162500,0.780000
Tomate,14.090000,13.495000,10.430000,-11.960000,-15.375000,2.220000,-5.140000,8.680000,-1.345000,3.140000,...,15.825000,13.785000,-7.635000,2.710000,-5.205000,-12.205000,-7.745000,0.620000,-6.435000,11.315000
Trigo,0.532222,-0.076667,-0.077778,-0.038889,0.361111,0.677778,1.046667,1.047778,1.520000,0.302222,...,0.935556,0.078889,-0.068889,-0.560000,-0.054444,-0.443333,-0.361111,0.555556,-0.204444,0.167778

In [66]:
data.to_csv('IPCA_DADOS_AGRUPADOS.csv',index=True, sep=';', encoding = 'Latin1')